version: '3.4'

x-napalm: &napalm_proxy
  image: salt_napalm
  build:
    context: ./napalm_proxy
  environment:
    SALT_PROXY_CONFIG: '{"log_level":"error"}'

x-minion: &minion
  image: saltstack/salt
  user: root
  environment:
    SALT_MINION_CONFIG: '{}'


services:
  # MASTER
  salt:
    image: saltstack/salt
    ports:
      - 8000:8000
    volumes:
      - ./data:/srv
    env_file:
      - .env
    environment:
      SALT_MASTER_CONFIG: '{"log_level":"error"}'

  # MINION
  minion1:
    <<: *minion
    hostname: minion1

  minion2:
    <<: *minion
    hostname: minion2


  # PROXY
  # CN POD X
  sw01:
    <<: *napalm_proxy
    environment:
      SALT_PROXY_ID: sw01${hostname_suffix}
  sw02:
    <<: *napalm_proxy
    environment:
      SALT_PROXY_ID: sw02${hostname_suffix}
  sw03:
    <<: *napalm_proxy
    environment:
      SALT_PROXY_ID: sw03${hostname_suffix}
  sw04:
    <<: *napalm_proxy
    environment:
      SALT_PROXY_ID: sw04${hostname_suffix}
